config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/admins/sessions",
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }

  root to: "homes#top"
  get "homes/about"
  
  resources :rooms do
    resources :messages
  end
  
  post 'create_myroom', to: 'rooms#create_myroom'
  
  resources :users, only: [:show, :edit, :update]
  
  resources :stray_cats do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :protective_cats do
    resource :p_favorites, only: [:create, :destroy]
    resources :p_post_comments, only: [:create, :destroy]
  end

  namespace :admin do
    get "/" => 'homes#index'
    get 'comments/index'
    resources :users, only: [:index, :show, :destroy]
   resources :comments, only: [:index, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image
  has_many :stray_cats, dependent: :destroy
  has_many :protective_cats, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :p_post_comments, dependent: :destroy
  has_many :p_favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users

#validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: true
validates :last_name, presence: true

    def get_profile_image(width, height)
    unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  profile_image.variant(resize_to_limit: [width, height]).processed
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   layout 'admin'
def index
   @users = User.all

end

# def edit
#   @customer = Customer.find(params[:id])
# end

def show
  @user = User.find(params[:id])

end



def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/admin/users'
end

private

# def user_params
#   params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number)
# end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
def after_sign_up_path_for(resource)
    user_path(resource)
end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]
 before_action :authenticate_user!, except: [:top, :about]

  def show
    @user = User.find(params[:id])
    @stray_cats = @user.stray_cats.page(params[:page])
    @protective_cats = @user.protective_cats.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to users_path
    end
  end

  def update
  if @user = current_user
  @user.update(user_params)
  redirect_to user_path(@user.id)
  else
          render :edit
  end
  end

  private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 
 <div class="col-sm-12 col-md-2">
<h2>プロフィール編集</h2>
<p><%= @user.nickname %>の会員情報編集</p>
<%= form_with model: @user,url: user_path(@user.id), method: :PATCH do |f| %>


 <div>画像<%= f.file_field :profile_image, accept: "image/*" %></div>

  <label for="inputLast_name">氏名</label>
  <div class="input-groups"><%= f.text_field :last_name, autofocus: true, id:"inputLast_name", placeholder:"Last_name"%>

  <label for="inputFirst_name"></label>
  <%= f.text_field :first_name, autofocus: true, id:"inputFirst_name", placeholder:"First_name"%></div>

  <label for="inputLast_name_kana">フリガナ</label>
  <div class="input-groups"><%= f.text_field :last_name_kana, autofocus: true, id:"inputLast_name_kana", placeholder:"Last_name_kana"%>

  <label for="inputFirst_name_kana"></label>
  <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirst_name_kana", placeholder:"First_name_kana"%></div>


  <label for="inputPostal_code">郵便番号</label>
  <div><%= f.text_field :postal_code, autofocus: true, id:"inputPostal_code", placeholder:"Postal_code"%></div>

  <label for="inputAddress">住所</label>
  <div><%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder:"Address"%></div>

  <label for="inputTelephone_number">電話番号</label>
  <div><%= f.text_field :telephone_number, autofocus: true, id:"inputTelephone_number", placeholder:"Telephone_number"%></div>

  <label for="inputEmail">メールアドレス</label>

  <div><%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"Email"%></div>


  <div><%= f.submit "変更を保存" %></div>

<% end %>

</div>

app/views/users/show.html.erb
<div class="col-sm-12 col-md-2">
  <h3><%= @user.nickname %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
   <% if @user == current_user %>
    <p><%= link_to "Edit profile", edit_user_path(@user) %>
    </p>
  <% end %>

<div>
  <% if @user == current_user %>
    <%= link_to "Chat Room Index", rooms_path %>
  <% else %>
    <%= form_with(url: create_myroom_path, local: true) do |f| %>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.submit "send message" %>
    <% end %>
  <% end %>

 </div>

</div>
<body class="d-flex flex-column vh-100">
<main class ="mb-auto">
    <div class="post-detail py-5 bg-light">
      <div class="container">
        <div class="card mx-auto mt-4 shadow-lg">

<%= render 'stray_cats/list', stray_cats: @stray_cats %>

<%= render 'protective_cats/list', protective_cats: @protective_cats %>

</div>
        </div>
  </div>
</main>
 </body>