config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/admins/sessions",
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }

  root to: "homes#top"
  get "homes/about"
  
  resources :rooms do
    resources :messages
  end
  
  post 'create_myroom', to: 'rooms#create_myroom'
  
  resources :users, only: [:show, :edit, :update]
  
  resources :stray_cats do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :protective_cats do
    resource :p_favorites, only: [:create, :destroy]
    resources :p_post_comments, only: [:create, :destroy]
  end

  namespace :admin do
    get "/" => 'homes#index'
    get 'comments/index'
    resources :users, only: [:index, :show, :destroy]
   resources :comments, only: [:index, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :stray_cat

  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image
end

app/models/p_favorite.rb
class PFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :protective_cat
  
end

app/models/p_post_comment.rb
class PPostComment < ApplicationRecord
  belongs_to :user
  belongs_to :protective_cat
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :stray_cat
  
  
end

app/models/protective_cat.rb
class ProtectiveCat < ApplicationRecord
    has_one_attached :image
  belongs_to :user
  has_many :p_post_comments, dependent: :destroy
  has_many :p_favorites, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    p_favorites.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["color", "place", "caption", "name", "neuter", "gender", "health" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["p_favorites", "image_attachment", "image_blob", "p_post_comments", "user"]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  scope :myrooms, -> (user) { where(user_id: user.id).or(where(owner_id: user.id)) }
  
  belongs_to :user
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  
  has_many :messages, dependent: :destroy
  
  def room_partner(current_user)
    user_data = [owner_id, user_id]
    User.find(user_data.select{|id| id != current_user.id }).first
  end
  
  def self.myroom(current_user, user_id)
     where(owner_id: current_user.id, user_id: user_id).or(where(owner_id: user_id, user_id: current_user.id)).first
  end
end

app/models/stray_cat.rb
class StrayCat < ApplicationRecord
    has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: true

   geocoded_by :address
   after_validation :geocode, if: :address_changed?

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["color", "place", "caption"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["favorites", "image_attachment", "image_blob", "post_comments", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image
  has_many :stray_cats, dependent: :destroy
  has_many :protective_cats, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :p_post_comments, dependent: :destroy
  has_many :p_favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users

#validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: true
validates :last_name, presence: true

    def get_profile_image(width, height)
    unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  profile_image.variant(resize_to_limit: [width, height]).processed
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/p_favorites_helper.rb
module PFavoritesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/stray_cats_helper.rb
module StrayCatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><!--<br />-->
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><!-- <br />--
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |messages| %>
      <li><%= messages %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

  <script src="https://kit.fontawesome.com/4a5b37bc44.js" crossorigin="anonymous"></script>

<head>
  <title>nyanstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
          <span>Nyanstagram</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">


            <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_path, class: 'nav-link text-light' do %>
            <i class="fa-solid fa-pen"></i> Top
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to admin_users_path, class: 'nav-link text-light' do %>
             <i class="fa-solid fa-users"></i> Users
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to admin_comments_index_path, class: 'nav-link text-light' do %>
            <i class="fa-regular fa-comment"></i> Comments
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-out-alt"></i> Log out
             <% end %>
            </li>

            <% else %>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
     <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <script src="https://kit.fontawesome.com/4a5b37bc44.js" crossorigin="anonymous"></script>

<head>
  <title>nyanstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
          <span>Nyanstagram</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">


            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
            <i class="fas fa-home"></i> My_page
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to protective_cats_path, class: 'nav-link text-light' do %>
            <i class="fa-solid fa-shield-cat"></i> Protective_cats
             <% end %>
            </li>

            <li class="nav-item">
            <%= link_to stray_cats_path, class: 'nav-link text-light' do %>
             <i class="fa-solid fa-paw"></i> Stray_cats
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to rooms_path, class: 'nav-link text-light' do %>
            <i class="fa-solid fa-envelope"></i> DM
             <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-out-alt"></i> Log out
             <% end %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>

            <li class="nav-item">
             <%= link_to homes_about_path, class: 'nav-link text-light' do %>
            <i class="fas fa-link"></i> About
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <i class="fas fa-user-plus"></i> Sign up
             <% end %>
            </li>

            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-in-alt"></i> Log in
             <% end %>
            </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
     <%= yield %>
  </body>
</html>