config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/admins/sessions",
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }

  root to: "homes#top"
  get "homes/about"
  
  resources :rooms do
    resources :messages
  end
  
  post 'create_myroom', to: 'rooms#create_myroom'
  
  resources :users, only: [:show, :edit, :update]
  
  resources :stray_cats do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :protective_cats do
    resource :p_favorites, only: [:create, :destroy]
    resources :p_post_comments, only: [:create, :destroy]
  end

  namespace :admin do
    get "/" => 'homes#index'
    get 'comments/index'
    resources :users, only: [:index, :show, :destroy]
   resources :comments, only: [:index, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :stray_cat

  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image
end

app/models/p_favorite.rb
class PFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :protective_cat
  
end

app/models/p_post_comment.rb
class PPostComment < ApplicationRecord
  belongs_to :user
  belongs_to :protective_cat
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :stray_cat
  
  
end

app/models/protective_cat.rb
class ProtectiveCat < ApplicationRecord
    has_one_attached :image
  belongs_to :user
  has_many :p_post_comments, dependent: :destroy
  has_many :p_favorites, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    p_favorites.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["color", "place", "caption", "name", "neuter", "gender", "health" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["p_favorites", "image_attachment", "image_blob", "p_post_comments", "user"]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  scope :myrooms, -> (user) { where(user_id: user.id).or(where(owner_id: user.id)) }
  
  belongs_to :user
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  
  has_many :messages, dependent: :destroy
  
  def room_partner(current_user)
    user_data = [owner_id, user_id]
    User.find(user_data.select{|id| id != current_user.id }).first
  end
  
  def self.myroom(current_user, user_id)
     where(owner_id: current_user.id, user_id: user_id).or(where(owner_id: user_id, user_id: current_user.id)).first
  end
end

app/models/stray_cat.rb
class StrayCat < ApplicationRecord
    has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: true

   geocoded_by :address
   after_validation :geocode, if: :address_changed?

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["color", "place", "caption"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["favorites", "image_attachment", "image_blob", "post_comments", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image
  has_many :stray_cats, dependent: :destroy
  has_many :protective_cats, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :p_post_comments, dependent: :destroy
  has_many :p_favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users

#validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: true
validates :last_name, presence: true

    def get_profile_image(width, height)
    unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  profile_image.variant(resize_to_limit: [width, height]).processed
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/protective_cats_controller.rb
class ProtectiveCatsController < ApplicationController
  def new
    @protective_cat = ProtectiveCat.new
  end

  def create
    @protective_cat = ProtectiveCat.new(protective_cat_params)
    @protective_cat.user_id = current_user.id
  if @protective_cat.save
    redirect_to protective_cat_path(@protective_cat.id)
  else
      render :new
  end

  end

  def index
    @q =  ProtectiveCat.ransack(params[:q])
    @protective_cats = @q.result(distinct: true).includes(:user).page(params[:page]).order("created_at desc")

  end


  def show
    @protective_cat = ProtectiveCat.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    protective_cat = ProtectiveCat.find(params[:id])
    protective_cat.destroy
    redirect_to protective_cats_path
  end


 private

  def protective_cat_params
    params.require(:protective_cat).permit(:name, :image, :caption, :neuter, :color, :place, :gender, :health)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/p_favorites_helper.rb
module PFavoritesHelper
end

app/helpers/protective_cats_helper.rb
module ProtectiveCatsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/stray_cats_helper.rb
module StrayCatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/protective_cats/_list.html.erb
<div class="card-list-container py-5">
  <% protective_cats.each do |p_cat| %>
   <div class="card w-100 mx-auto mt-4 shadow-lg">
    <%= link_to protective_cat_path(p_cat.id) do %>
      <%= image_tag(p_cat.image.variant(resize: "640X640^", crop: "640x640+0+0").processed, class:"card-img-top") %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-3">
          <%= image_tag p_cat.user.get_profile_image(100,100), class:"mt-3 rounded-circle img-fluid" %>
        </div>
        <div class="col-9">
          <p class="card-title">
            <%= link_to(protective_cat_path(p_cat.id), class:"text-dark") do %>

            <% end %>
          </p>
          <p class="card-text">説明：<%= p_cat.caption %></p>
          <p>
          <span><i class="fas fa-user"></i> By <%= p_cat.user.nickname %> ｜ </span>
          <span><%= link_to "#{p_cat.p_post_comments.count} Comment", protective_cat_path(p_cat.id), class:"text-dark" %> | </span>

          <span><% if p_cat.favorited_by?(current_user) %>

                  <%= link_to protective_cat_p_favorites_path(p_cat), method: :delete do %>
                    ♥<%= p_cat.p_favorites.count %> いいね
                  <% end %>

                   <% else %>
                    <%= link_to protective_cat_p_favorites_path(p_cat), method: :post do %>
                    ♡<%= p_cat.p_favorites.count %> いいね
                  <% end %>

                  <% end %>
            </span>
            </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate protective_cats %>
</div>

app/views/protective_cats/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
   <%= f.search_field :caption_or_color_or_place_or_name_or_neuter_or_gender_or_health_cont, class: 'form-control', placeholder: '検索ワード' %>
   <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>

app/views/protective_cats/_search.htmll.erb
<%= search_form_for @q, url: url do |f| %>
   <%= f.search_field :caption_or_color_or_place_cont, class: 'form-control', placeholder: '検索ワード' %>
   <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>

app/views/protective_cats/edit.html.erb
<h1>ProtectiveCats#edit</h1>
<p>Find me in app/views/protective_cats/edit.html.erb</p>

app/views/protective_cats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
     <h1>ProtectiveCats#index</h1>
     
      <div class="mt-4">
        <%= render 'search', q: @q, url: protective_cats_path %>
      </div>
    <%= link_to '新規投稿', new_protective_cat_path, class: "btn btn-primary mt-4" %>
    <%= render 'list', protective_cats: @protective_cats %>
     </div>
  </div>
</div>

app/views/protective_cats/new.html.erb
<h1>ProtectiveCats#new</h1>
<h1>画像投稿フォーム</h1>
<%= form_with model: @protective_cat do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>名前</h4>
  <%= f.text_area :name %>
  
 <h4>色</h4>
  <%= f.text_area :color %>
  <h4>性別</h4>
  <%= f.text_area :gender %>
  <h4>避妊/去勢</h4>
  <%= f.text_area :neuter %>
  <h4>健康状態</h4>
  <%= f.text_area :health %>
  
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/protective_cats/show.html.erb
<body class="d-flex flex-column vh-100">
<main class ="mb-auto">
  <div class="post-detail py-5 bg-light">
    <div class="container">
    　<div class="card mx-auto mt-4 shadow-lg">
        <%= image_tag @protective_cat.get_image %>
        <div class="card-body">
          <div class="row">
            <div class="col-3 col-lg-2">
              <%= image_tag @protective_cat.user.get_profile_image(100,100), class:"mt-3 rounded-circle img-fluid"; %>
            </div>

            <div class="col-9 col-lg-10 pt-4">
              <p class="card-text">名前：<%= @protective_cat.name %></p>
              <p class="card-text">色：<%= @protective_cat.color %></p>
              <p class="card-text">性別：<%= @protective_cat.gender %></p>
              <p class="card-text">不妊・去勢：<%= @protective_cat.neuter %></p>
              <p class="card-text">健康状態：<%= @protective_cat.health %></p>
              <p class="card-text">説明：<%= @protective_cat.caption %></p>

              <span><i class="fa-solid fa-user"></i>
              By <%= link_to user_path(@protective_cat.user.id) do %>
              <%= @protective_cat.user.nickname %><% end %> | </span>
              <span><i class="fa-regular fa-calendar-days"></i><%= @protective_cat.created_at.strftime('%Y/%m/%d') %> | </span>
              <span><i class="fa-regular fa-comment"></i><%= @protective_cat.p_post_comments.count %> | </span>
              <span>♡<%= @protective_cat.p_favorites.count %> いいね | </span>
              <span><% if @protective_cat.user == current_user %>
                      <%= link_to "削除", protective_cat_path(@protective_cat), method: :delete %>
                        <% end %>
              </span>
                      </div>
                    </div>
                  </div>
                <hr>
              <div>
          <h4 class="col-sm-12 col-md-2 p-3 text-center">Comments</h4>
            <% @protective_cat.p_post_comments.each do |p_post_comment| %>
            <div class="row">
              <div class="p-3 text-center col-md-4">
                <div><%= image_tag p_post_comment.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %></div>
                 <p><%= link_to user_path(@protective_cat.user.id) do %>
                      <%= p_post_comment.user.nickname %></p>
                      <% end %>
              </div>
              <div class="p-3 col-md-4">
                 <p class="card-text"><%= p_post_comment.comment %></p>
                   <%= p_post_comment.created_at.strftime('%Y/%m/%d') %> |
                    <% if p_post_comment.user == current_user %>
                    <%= link_to "削除", protective_cat_p_post_comment_path(@protective_cat, p_post_comment), method: :delete %>
                  <% end %>
              </div>
            </div>
            <% end %>
        <hr>
        <div class="new-comment card-text">
          <%= form_with model: [@protective_cat, @post_comment], url: protective_cat_p_post_comments_path(@protective_cat.id) do |f| %>
           <textarea rows="5" class="form-control" placeholder="コメントをここに" name="post_comment[comment]" id="post_comment_comment"></textarea>
            <input type="submit" name="commit" value="送信する" class="btn btn-lg btn-info mt-2 float-right" data-disable-with="送信する">
          <% end %>
        </div>
       </div>
      </div>
    </div>
  </div>
</main>
</body>